version: '3.8'
services:
  aa-bot:
    image: aa-bot
    container_name: aa-bot
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "3000:3000"
    restart: always
